# Generated by Django 5.0.6 on 2024-05-27 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answer_is_anonymous_alter_answer_profile'),
        ('questions', '0009_alter_question_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anonymous_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('profile', 'question', 'anonymous_token')},
        ),
    ]
