# Generated by Django 5.0.6 on 2025-12-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_answer_anonymous_token_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
