# Generated by Django 5.0.6 on 2025-12-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
