# Generated by Django 5.0.6 on 2024-05-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questionoption_options_questionoption_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
