# Generated by Django 5.0.6 on 2024-05-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_questionoption_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='order',
        ),
    ]
