# Generated by Django 5.0.6 on 2024-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_options_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
