# Generated by Django 5.0.6 on 2024-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionoption_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-creation_date']},
        ),
    ]
