# Generated by Django 5.0.6 on 2025-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
