# Generated by Django 5.0.6 on 2025-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('binary', 'Binaria (Sí/No)'), ('scale', 'Escala (1-5)'), ('dropdown', 'Lista desplegable')], default='binary', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
