# Generated by Django 5.0.6 on 2025-12-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_rating_average_question_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('binary', 'Binaria (Sí/No)'), ('scale', 'Escala (1-5)'), ('dropdown', 'Lista desplegable'), ('open', 'Abierta (Texto)')], default='binary', max_length=20),
        ),
    ]
