# Generated by Django 5.0.6 on 2025-12-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('binary', 'Binaria (Sí/No)'), ('scale', 'Escala (1-5)'), ('dropdown', 'Lista desplegable'), ('open', 'Abierta (Texto)'), ('slider', 'Deslizador (Rango)')], default='binary', max_length=20),
        ),
    ]
