# Generated by Django 5.0.6 on 2025-12-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['id']},
        ),
    ]
