# Generated by Django 5.0.6 on 2026-01-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_questionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('binary', 'Binaria (Sí/No)'), ('scale', 'Escala (1-5)'), ('dropdown', 'Lista desplegable'), ('open', 'Abierta (Texto)'), ('slider', 'Deslizador (Rango)'), ('date', 'Fecha (Calendario)')], default='binary', max_length=20),
        ),
    ]
