# Generated by Django 5.0.6 on 2024-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rut',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
