# Generated by Django 5.0.6 on 2025-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_votes_visible',
            field=models.BooleanField(default=True),
        ),
    ]
