# Generated by Django 5.0.6 on 2025-12-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_is_votes_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_birth_year_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_gender_public',
            field=models.BooleanField(default=True),
        ),
    ]
