# Generated by Django 5.0.6 on 2025-12-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_is_birth_year_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
    ]
