# Generated by Django 5.0.6 on 2025-12-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_birth_date_profile_civil_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_birth_date_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_civil_status_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_education_level_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_nationality_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_profession_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
    ]
